### ISSUE TITLE
do we really need a population?

### ISSUE THREAD

**Issue by gstvrmrlpz** [JJ/energy-bbob#17]
If no SGA is used, why do we need the population?
Only memory allocation is exercised not floating point calculations...

Can I remove it leaving the next cycle:
1) generate random individual
2) evaluate individual

**Comment by JJ** [comment]
> If no SGA is used, why do we need the population? Only memory allocation is exercised not floating point calculations...

Because the methodology we're using calls for computing a baseline measurement that excludes the actual function we are measuring. We have used so far generation for that. We can also measure the efficiency of the RNGs for floats here.
 
> Can I remove it leaving the next cycle:
> 
>     1. generate random individual

No, as we did for binary chromosomes, there should be a loop for generating 40000 individuals (we might want to compare energy consumption across types of functions), and then...
> 
>     2. evaluate individual

A loop to evaluate the 40000 individuals, *exactly the same we did before*

**Comment by gstvrmrlpz** [comment]
resolved
